import "css/tailwind";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} selection:bg-blue-100/80 grid grid-rows-[auto_1fr]`}>
        <header className="sticky top-0 z-40 backdrop-blur bg-white/95">
          <div className="grid grid-cols-[1fr_auto_1fr] px-14 py-3 items-center max-w-[86rem] mx-auto">
            <div>
              <Link href="/" className="text-lg">
                <span className="font-bold text-slate-800">Astro</span>
                <span className="text-slate-500">ship</span>
              </Link>
            </div>

            <nav>
              <ul className="flex text-sm">
                <li className="px-3 py-2 text-gray-600 hover:text-gray-900">Features</li>
                <li className="px-3 py-2 text-gray-600 hover:text-gray-900">Pricing</li>
                <li className="px-3 py-2 text-gray-600 hover:text-gray-900">About</li>

                <Link href="/posts" className="px-3 py-2 text-gray-600 hover:text-gray-900">
                  Blog
                </Link>

                <Link href="/studio" className="px-3 py-2 text-gray-600 hover:text-gray-900">
                  Studio
                </Link>
              </ul>
            </nav>

            <div className="flex items-center justify-end gap-4 text-sm">
              <button>Log in</button>
              <button className="rounded text-center px-4 py-2 bg-black text-white hover:bg-gray-800 border-2 border-transparent">Sign up</button>
            </div>
          </div>
        </header>

        <main className="w-full max-w-[86rem] mx-auto">{children}</main>
      </body>
    </html>
  );
}
